def error(op, num, msg):
  exit(print(f'\033[35mOperation {num + 1} raised an exception\nSource\npwease{op}\n{msg}'))
